### ISSUE TITLE
Handle modules controllers

### ISSUE THREAD

**Issue by ZiZuu-store** [ZiZuu-store/PrestaShop_module-zzSEOtk#11]
Nowadays modules' controllers are not handled .. so module-ph_simpleblog-list will give a wrong canonical URL

**Comment by ZiZuu-store** [comment]
@Chrisi1321 please gimme feedback on the current dev

Thanks

**Comment by Chrisi1321** [comment]
Sorry, not working...

**Comment by ZiZuu-store** [comment]
can you try to debug somehow?  I have no module with a controller installed on my shop AFAIK ...

**Comment by Chrisi1321** [comment]
I don't know how do to that...

**Comment by ZiZuu-store** [comment]
Just committed a simple mod .. plz try .. 

otherwise try to dump some vars .. `var_dump($params)`, `echo Tools::getValue('fc')`, `echo Tools::getValue('module')`

**Comment by Chrisi1321** [comment]
Now the blog doesn't load at all...

**Comment by Chrisi1321** [comment]
could you send me a mail to christopherhohl@gmail.com, I think it's better for communication...

**Comment by ZiZuu-store** [comment]
I'll install simple blog too on Monday ..
Will be able to debug, stay tuned

Il venerdì 24 luglio 2015, Chrisi1321 <notifications@github.com> ha scritto:

> Now the blog doesn't load at all...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZiZuu-store/PrestaShop_module-zzSEOtk/issues/11#issuecomment-124567326>
> .
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by ZiZuu-store** [comment]
do you have any third party URL rewriting module installed too?

**Comment by Chrisi1321** [comment]
Hi!
Yes it is called "Welutions Friendly URLs".

I would like to delete it and install your module, but I am a bit afraid that the site won't work anymore...

**Comment by ZiZuu-store** [comment]
If you intend "our" Clean url don't do it .. it is a try to rewrite and maintain a module being devoloped by someone else and in which we are still experimenting ..  zzSEOtk is written from scratch by us, clean urls not .. so if you are ok with a "clean url" module that works fine (even handling blogs for example" don't change


I just discovered a stupid error in the module .. plz check now and let see what happens :)

**Comment by Chrisi1321** [comment]
500 server error :(

**Comment by ZiZuu-store** [comment]
uhmm ... and no apache error log available?

**Comment by Chrisi1321** [comment]
I am not sure if thats important:

[Mon Jul 27 16:41:30 2015] [error] [client 199.27.128.240] File does not exist: /home/.sites/722/site4724782/web/js/admin/login.js/, referer: https://www.n1.ee/

**Comment by Chrisi1321** [comment]
but the site works well, except when I try to open the blog - Then  I get the 500

**Comment by ZiZuu-store** [comment]
no the error is irrelevant .. you should have a 500 error in the logs saying what's happening 

Unfortunately my "clean url" does not handle the blog so I'm having no error now but url rewriting still does not work .. I'm tring to go deep in the clean url module to see if I can make it handle the blog ...

I installed ph_simple_blog ... is the same of your blog ?

**Comment by Chrisi1321** [comment]
Hi!
Thanks...
Yes I have installed the same blog.

**Comment by ZiZuu-store** [comment]
Do you think "Welutions Friendly URLs" is working well ? I can think of dismiss our "clean url" and go to this one if it is well coded and maintained ...

What is your opinion?

**Comment by ZiZuu-store** [comment]
OK got the error .. working on a fix .. it's not the clean url module .. it's the canonical

stay tuned

**Comment by Chrisi1321** [comment]
The Url rewriting module works well, even with the blog. 
Unfortunately the module is not maintained anymore ,and not available on codecanyon anymore.

I can share it with you if you want...

**Comment by ZiZuu-store** [comment]
OK after a long debugging I removed both zzcleanurls and zzseotk. then switched on "disable overrides" 

the ph_simple_blog module still gives 500 error .. it seems to lack a parameter (sb_category) .. 
We can't find a way to have the blog to work on our shop ..

**Comment by Chrisi1321** [comment]
Is there a way to disable the canonical url just for the blog? 
That would be a first workaround....
Can you try to contact the developer of the blog? Perhaps he will fix it soon...

**Comment by ZiZuu-store** [comment]
For me the blog does not work even without my module!

no relation with canonical or whatever else ..  going to eat now .. tomorrow will write to the blog devel (as we payed for it :P )

**Comment by ZiZuu-store** [comment]
@Chrisi1321 Ok after a long debug I found that our problem with ph_simple_blog was given by a theme template .. 

After having ph_simple_blog working I fixed the canonical too ... now it is working perfectly on my server ..

Hope on yours too :)

**Comment by Chrisi1321** [comment]
Almost :) 
Take a look at my blog 

https://www.aktiv-naturheilmittel.at/blog/news/pfefferminze-mehr-als-nur-fur-den-hugo

hreflangs are following:

<link rel="alternate" hreflang="de-at" href="https://www.aktiv-naturheilmittel.at/blog/news/pfefferminze-mehr-als-nur-fur-den-hugo"/>

<link rel="alternate" hreflang="de-de" href="https://www.aktiv-naturheilmittel.de/module/ph_simpleblog/single?sb_category=news&amp;rewrite=pfefferminze-mehr-als-nur-fur-den-hugo"/>

<link rel="alternate" hreflang="de-ch" href="https://www.aktiv-naturheilmittel.ch/module/ph_simpleblog/single?sb_category=news&amp;rewrite=pfefferminze-mehr-als-nur-fur-den-hugo"/>

<link rel="canonical" href="https://www.aktiv-naturheilmittel.at/blog/news/pfefferminze-mehr-als-nur-fur-den-hugo"/>

**Comment by Chrisi1321** [comment]
oh I can't copy the links...

just take a look at the source :)

**Comment by ZiZuu-store** [comment]
Ok .. got the issue .. as I can't test on my server you have to be patient for a bit while  :)

**Comment by ZiZuu-store** [comment]
@Chrisi1321 plz try now

**Comment by Chrisi1321** [comment]
thanks for your effort, but still the same issue :(

**Comment by ZiZuu-store** [comment]
Are you sure you are using the dev branch ??
You should have no QS at all now ..

Il giovedì 30 luglio 2015, Chrisi1321 <notifications@github.com> ha scritto:

> thanks for your effort, but still the same issue :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZiZuu-store/PrestaShop_module-zzSEOtk/issues/11#issuecomment-126307738>
> .
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by Chrisi1321** [comment]
Yes I used the dev branch....

**Comment by Chrisi1321** [comment]
tried the newest fix....

now i have on the de_de and de_ch 

.../module/ph_simpleblog/single

**Comment by ZiZuu-store** [comment]
@Chrisi1321  another try :)

**Comment by Chrisi1321** [comment]
Same issue :(

**Comment by Chrisi1321** [comment]
do you think the issue is related to my URL rewrite module?
I can send it to you if you want...

**Comment by ZiZuu-store** [comment]
@Chrisi1321 maybe .. I can't reproduce

I just pushed a version having a comment around line 260 .. please uncomment it and report the output (its printed only for your maintenance IP)

**Comment by Chrisi1321** [comment]
I have uncommented it, uploaded it and added my IP to the maintenance mode.
What shall i report now?

**Comment by ZiZuu-store** [comment]
see the HTML source code .. look for XXX

**Comment by Chrisi1321** [comment]
can't find a xxx

**Comment by Chrisi1321** [comment]
can you print it for every ip?

**Comment by Chrisi1321** [comment]
however the canonical tag works perfect, only the hreflang tags are not correct...

<link rel="alternate" hreflang="de-de" href="https://www.aktiv-naturheilmittel.de/module/ph_simpleblog/single"/>

**Comment by Chrisi1321** [comment]
<link rel="alternate" hreflang="de-de" href="https://www.aktiv-naturheilmittel.de/module/ph_simpleblog/single"/>

**Comment by Chrisi1321** [comment]
link rel="alternate" hreflang="de-at" href="https://www.aktiv-naturheilmittel.at/blog/news/pfefferminze-mehr-als-nur-fur-den-hugo"

link rel="alternate" hreflang="de-de" href="https://www.aktiv-naturheilmittel.de/module/ph_simpleblog/single"/

link rel="alternate" hreflang="de-ch" href="https://www.aktiv-naturheilmittel.ch/module/ph_simpleblog/single"

**Comment by ZiZuu-store** [comment]
Yes I'm looking to the source too ..

if you want to enable the debug for every IP simply remove the if()

**Comment by Chrisi1321** [comment]
done...

**Comment by Chrisi1321** [comment]
XXX
string(36) "https://www.aktiv-naturheilmittel.at" int(1) array(10) { ["id_lang"]=> string(1) "3" ["name"]=> string(17) "Deutsch (Austria)" ["active"]=> string(1) "1" ["iso_code"]=> string(2) "de" ["language_code"]=> string(5) "de-at" ["date_format_lite"]=> string(5) "d.m.Y" ["date_format_full"]=> string(11) "d.m.Y H:i:s" ["is_rtl"]=> string(1) "0" ["id_shop"]=> string(1) "1" ["shops"]=> array(1) { [1]=> bool(true) } } 
XXXXXX
string(36) "https://www.aktiv-naturheilmittel.de" int(2) array(10) { ["id_lang"]=> string(1) "1" ["name"]=> string(17) "Deutsch (Germany)" ["active"]=> string(1) "1" ["iso_code"]=> string(2) "de" ["language_code"]=> string(5) "de-de" ["date_format_lite"]=> string(5) "d.m.Y" ["date_format_full"]=> string(11) "d.m.Y H:i:s" ["is_rtl"]=> string(1) "0" ["id_shop"]=> string(1) "2" ["shops"]=> array(1) { [2]=> bool(true) } } 
XXXXXX
string(36) "https://www.aktiv-naturheilmittel.ch" int(3) array(10) { ["id_lang"]=> string(1) "4" ["name"]=> string(19) "Deutsch CH (German)" ["active"]=> string(1) "1" ["iso_code"]=> string(2) "de" ["language_code"]=> string(5) "de-ch" ["date_format_lite"]=> string(5) "d.m.Y" ["date_format_full"]=> string(11) "d.m.Y H:i:s" ["is_rtl"]=> string(1) "0" ["id_shop"]=> string(1) "3" ["shops"]=> array(1) { [3]=> bool(true) } } 
XXX

**Comment by ZiZuu-store** [comment]
ok now comment again and uncomment the other comment present in the file

**Comment by ZiZuu-store** [comment]
string(64) "https://www.aktiv-naturheilmittel.de/module/ph_simpleblog/single"
int(2)
array(10) {
["id_lang"]=>
string(1) "1"
["name"]=>
string(17) "Deutsch (Germany)"
["active"]=>
string(1) "1"
["iso_code"]=>
string(2) "de"
["language_code"]=>
string(5) "de-de"
["date_format_lite"]=>
string(5) "d.m.Y"
["date_format_full"]=>
string(11) "d.m.Y H:i:s"
["is_rtl"]=>
string(1) "0"
["id_shop"]=>
string(1) "2"
["shops"]=>
array(1) {
[2]=>
bool(true)
}
}

**Comment by Chrisi1321** [comment]
XXX
string(5) "index" bool(false) bool(false) 
XXXXXX
string(5) "index" bool(false) bool(false) 
XXXXXX
string(5) "index" bool(false) bool(false) 
XXXXXX
string(5) "index" bool(false) bool(false) 
XXXXXX
string(5) "index" bool(false) bool(false) 
XXX

**Comment by ZiZuu-store** [comment]
ok this seems all right ... I'll think about it this WE :)

Thank you

**Comment by Chrisi1321** [comment]
Perfect..thanks!

**Comment by ZiZuu-store** [comment]
But your C&P here is very different from what I have seen on your site .. maybe you had some issue with the C&P .. no problem .. seen the debug in real time ;)

string(6) "single"
string(13) "ph_simpleblog"
string(6) "module"

**Comment by ZiZuu-store** [comment]
I really can't find anything in my module ... I suppose your clean URL module is overriding Link::getModuleLink() ... the problem should be there

**Comment by Chrisi1321** [comment]
do you see an error in there? 
This is link.php

http://pastebin.com/1qJ7Zjgh

**Comment by ZiZuu-store** [comment]
No, This code does not override getModuleLink .. please try to send me this
module so I can install and reproduce

We are now using a different module and everything works for us

Il sabato 1 agosto 2015, Chrisi1321 <notifications@github.com> ha scritto:

> do you see an error in there?
> This is link.php
>
> http://pastebin.com/1qJ7Zjgh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZiZuu-store/PrestaShop_module-zzSEOtk/issues/11#issuecomment-126837090>
> .
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by Chrisi1321** [comment]
www.aktiv-naturheilmittel.at/friendlyurl.zip

**Comment by ZiZuu-store** [comment]
got and removed ... I'm taking a look

**Comment by ZiZuu-store** [comment]
@Chrisi1321 Lines around 435 of PS Dispatcher are quite newer than analogue lines in your the override Dispatcher of your module.

I think the issue could be in the language handling of your old Dispatcher ...

**Comment by Chrisi1321** [comment]
Do you have any recommendation how to change that?

**Comment by ZiZuu-store** [comment]
I'm using another module now .. but having some issue with it too (not related to canonical/hreflang) .. it seems it is quite impossible to find a perfect "clean URL" module .... 

The Simple Blog author said the FME clean url module should work fine .. if you want you can try it ..

**Comment by ZiZuu-store** [comment]
AFAICS this issue should be closed .. if any other problem arises please open a new issue for it ..

Thank you for helping in debugging 
Regards
